---
title: "Sesión 04"
date: "2022-10-10"
---

## Objetivos

[Disponible cuando se grabe esta clase]

## Materiales

::: {.panel-tabset}

### Clase grabada

[Disponible cuando se grabe esta clase]

### Slides

```{r slides-videos, echo=FALSE, include=FALSE}
source(here::here("R", "slide-things.R"))
```

```{r show-slide-tabs1, echo=FALSE, results="asis"}
slide_buttons("/slides/sesion04/sesion04")
```

```{=html}
<iframe width="780" height="500" src="../slides/sesion04/sesion04.html" title="Sesión 4 - Manejo de datos 2, AID/AED con R"></iframe>
```

### Talleres

|                              |                                                                                  |
|----------------------|--------------------------------------------------|
| Instructivo en línea         | [Aquí](../taller/taller04/taller04_instructivo.html)                                                 |
| Instructivo con solucionario | [Aquí](../taller/taller04/taller04_instructivo_solno.html)                                                                       |
| Quarto para alumnos          | [Aquí](../taller/taller04/taller04_alumno.qmd)                                                                       |
| Toda la carpeta del taller   | [Aquí](https://drive.google.com/drive/folders/1Iac8vod_FqXwDDPaOdIBsyw5uUfEx1Lb) |

:::


