---
title: "Sesión 07"
date: "2022-10-17"
---

## Objetivos

[Disponible cuando se grabe esta clase]

## Materiales

::: {.panel-tabset}

### Clase grabada

[Disponible cuando se grabe esta clase]

### Slides

```{r slides-videos, echo=FALSE, include=FALSE}
source(here::here("R", "slide-things.R"))
```

```{r show-slide-tabs1, echo=FALSE, results="asis"}
# slide_buttons("/slides/sesion07/sesion07_chalkboard-speaker")
```


### Talleres

|                              |                                                                                  |
|----------------------|--------------------------------------------------|
| Instructivo en línea         | [Aquí]()                                                 |
| Instructivo con solucionario | [Aquí]()                                                                       |
| Quarto para alumnos          | [Aquí]()                                                                       |
| Toda la carpeta del taller   | [Aquí](https://drive.google.com/drive/folders/1qDor0XJEtB9rW6yXWIfmc_mWXYz9MNTV) |

:::


